### ISSUE TITLE
Optional values should be optional

### ISSUE THREAD

**Issue by haizaar** [doitintl/terraform-provider-doit-console#11]
Following #9 and #10 I think it's a common thread in the current provider definitions that too many attributes are required while they shouldn't (that's according to developer.doit.com)

I think it worth going over all attributes and checking required/optional vs developer.doit.com

**Comment by dianibar** [comment]
I leave some optional values as required, because they are created by default and had values when they are read from the API, so I will leave this open for now

**Comment by dianibar** [comment]
Fixed in the new repo https://github.com/doitintl/terraform-provider-doit that is used by the new  provider published https://registry.terraform.io/providers/doitintl/doit/latest
