### ISSUE TITLE
Docs bug?

### ISSUE THREAD

**Issue by haizaar** [doitintl/terraform-provider-doit-console#3]
Looking at https://registry.terraform.io/providers/doitintl/doit-console/latest/docs, it says `doit-console-provider-name Provider` - shouldn't it be just doit-console Provider`?

![image](https://github.com/doitintl/terraform-provider-doit-console/assets/58201/176fc910-b79d-4512-9c51-ecc1fffe8cc3)

**Comment by dianibar** [comment]
I generate the documentation using the flag --provider-name: 
`go generate ./... --provider-name doit-console `

**Comment by haizaar** [comment]
Now it's better. Have you changed anything?
![Uploading image.png…]()

**Comment by haizaar** [comment]
Now it's better. Have you changed anything?
![image](https://github.com/doitintl/terraform-provider-doit-console/assets/58201/d1885054-8765-49b9-a5c7-8038d573ec11)

**Comment by dianibar** [comment]
I regenerate the docs including the option --provider-name doit-console it seems the default one has a bug
