### ISSUE TITLE
Rename `customercontext` to `customer_context`

### ISSUE THREAD

**Issue by haizaar** [doitintl/terraform-provider-doit-console#5]
Following TF style [guidelines](https://www.globaldots.com/resources/blog/terraform-naming-conventions-best-practices-a-hell-of-a-practical-guide/#:~:text=confusion%20and%20ambiguity.-,Use%20all%20lower%2Dcase%20with%20underscores%20as%20separators,with%20the%20HashiCorp%20naming%20conventions.), we should use Snake Case for property names, e.g.

`customercontext` -> `customer_context`

Can you please rename and release 0.**2**.x? (to avoid immediate breakages)

**Comment by dianibar** [comment]
fixed
